import turtle

screen = turtle.Screen()
screen.screensize(500,500)
screen.bgcolor("lightblue")

t = turtle.Turtle()
t.penup()
t.goto(-50,-50)
t.pendown()
t.pencolor("cyan")
t.fillcolor("cyan")
t.begin_fill()
t.setheading(45)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
t.penup()
t.goto(90,-50)
t.pendown()
t.pencolor("brown")
t.fillcolor("brown")
t.begin_fill()
t.setheading(45)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()
turtle.done()